name: ADVANCED WARFARE
favicon: null
layout_spectrum: 0.24724
typography_spectrum: 0.87882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0c0c0c'
    - '#181818'
    - '#262626'
    - '#504536'
  brandStrength: 0.8723614339251071
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.8619942823424935
purpose: []
